title: SCHH Hudson Valley Friends

description:The Webiste will provide  information and events relating to  the Sun City Hudson Valley Friends Group
  Website Description

author:
  name: Cynthia Zambri
  email: your cynjon26@gmail.com

nav_pages:
  - about.md
  - contact.md

max-width: 800px

show_excerpts: true
show_rss_feed: true
show_github_link: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

content_selector: div.post-content,div.home
